PRODUCT_CATALOG = [
    {
        "id": 1,
        "skuId": 1001,
        "category": "通勤穿搭",
        "coverText": "职场白衬衫",
        "name": "简约通勤白衬衫",
        "price": 199,
        "stock": 36,
        "rating": 4.8,
        "sales": 860,
        "sceneTags": ["面试", "通勤", "上班"],
        "styleTags": ["简约", "百搭", "干净"],
        "searchTags": ["衬衫", "白衬衫", "女装", "穿搭"],
        "summary": "适合面试、通勤和日常搭配，版型利落，当前库存充足。",
    },
    {
        "id": 2,
        "skuId": 1002,
        "category": "搭配单品",
        "coverText": "轻商务托特包",
        "name": "轻商务托特包",
        "price": 269,
        "stock": 18,
        "rating": 4.6,
        "sales": 520,
        "sceneTags": ["面试", "通勤", "上班"],
        "styleTags": ["百搭", "轻商务"],
        "searchTags": ["包", "托特包", "通勤包"],
        "summary": "容量适合电脑和资料，风格与面试场景匹配。",
    },
    {
        "id": 3,
        "skuId": 1003,
        "category": "运动爆款",
        "coverText": "缓震跑鞋",
        "name": "缓震透气跑步鞋",
        "price": 429,
        "stock": 42,
        "rating": 4.9,
        "sales": 1280,
        "sceneTags": ["运动", "跑步", "训练"],
        "styleTags": ["轻便", "透气", "缓震"],
        "searchTags": ["运动鞋", "跑步鞋", "鞋"],
        "summary": "适合日常跑步训练，缓震中底降低膝盖压力，鞋面透气。",
    },
    {
        "id": 4,
        "skuId": 1004,
        "category": "运动搭配",
        "coverText": "速干短袖",
        "name": "速干训练短袖",
        "price": 129,
        "stock": 57,
        "rating": 4.5,
        "sales": 730,
        "sceneTags": ["运动", "跑步", "健身"],
        "styleTags": ["速干", "轻薄"],
        "searchTags": ["短袖", "运动服", "训练服"],
        "summary": "适合搭配跑步鞋组成基础运动套装，轻薄速干。",
    },
    {
        "id": 5,
        "skuId": 1005,
        "category": "高价过滤样例",
        "coverText": "高端西装",
        "name": "高端羊毛西装外套",
        "price": 899,
        "stock": 9,
        "rating": 4.7,
        "sales": 120,
        "sceneTags": ["面试", "商务"],
        "styleTags": ["正式", "高级"],
        "searchTags": ["西装", "外套"],
        "summary": "价格较高，适合正式商务场景。",
    },
    {
        "id": 6,
        "skuId": 1006,
        "category": "库存过滤样例",
        "coverText": "断码皮鞋",
        "name": "断码商务皮鞋",
        "price": 259,
        "stock": 0,
        "rating": 4.4,
        "sales": 310,
        "sceneTags": ["面试", "通勤"],
        "styleTags": ["商务"],
        "searchTags": ["皮鞋", "鞋"],
        "summary": "当前无库存，应被推荐过滤。",
    },
]
